'use client';
import { useEffect, useMemo, useState } from 'react';

const LEVELS=[{id:0,label:'সাধারণ প্রতিক্রিয়া',note:'সংক্ষিপ্ত ও তুলনামূলক সাধারণ মন্তব্য'},{id:1,label:'নির্দিষ্ট প্রতিক্রিয়া',note:'কাহিনি বা চরিত্রের নির্দিষ্ট দিক নিয়ে মন্তব্য'}];
type Attempt={attempt:number;retrieved:string[];draft:string;neural_score:number;symbolic_score:number;verdict:'PASS'|'FAIL';feedback:string|null;failed_rules:string[]};
type Faithfulness={status:'supported'|'review'|'unsupported'|'check_failed';support_score:number|null;explanation:string;unsupported_claims:string[];model:string;standing:string};
type LevelOutput={target_level:number;final:Attempt;attempts:Attempt[];gave_up:boolean;writer_calls:number;reflector_calls:number;llm_calls:number;faithfulness:Faithfulness};
type DemoResult={outputs:LevelOutput[]};
const FAITH_LABEL={supported:'প্লট-সমর্থিত',review:'পর্যালোচনা প্রয়োজন',unsupported:'অসমর্থিত তথ্য আছে',check_failed:'যাচাই সম্পন্ন হয়নি'};

export default function Home(){
 const[plot,setPlot]=useState('');const[target,setTarget]=useState<'both'|'0'|'1'>('both');const[loading,setLoading]=useState(false);const[online,setOnline]=useState<boolean|null>(null);const[error,setError]=useState('');const[result,setResult]=useState<DemoResult|null>(null);const chars=useMemo(()=>plot.trim().length,[plot]);const base=process.env.NEXT_PUBLIC_DEMO_API_URL||'http://localhost:8000';
 useEffect(()=>{fetch(`${base}/api/health`).then(r=>setOnline(r.ok)).catch(()=>setOnline(false))},[base]);
 async function generate(){if(!plot.trim()||loading)return;setLoading(true);setError('');setResult(null);const levels=target==='both'?[0,1]:[Number(target)];const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),600000);try{const response=await fetch(`${base}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({plot:plot.trim(),target_levels:levels,request_id:crypto.randomUUID().replaceAll('-','')})});const payload=await response.json().catch(()=>({detail:`Backend HTTP ${response.status}`}));if(!response.ok)throw new Error(payload.detail||`Backend HTTP ${response.status}`);setOnline(true);setResult(payload as DemoResult)}catch(err){setOnline(false);setError(err instanceof DOMException&&err.name==='AbortError'?'১০ মিনিটেও request শেষ হয়নি। Backend logs দেখে আবার চেষ্টা করুন।':err instanceof Error?err.message:'অনুরোধটি সম্পন্ন হয়নি')}finally{clearTimeout(timer);setLoading(false)}}
 return <main className="productShell">
  <header className="productNav"><a href="/" className="productBrand"><span>অ</span><b>Audience Response Lab</b></a><a href="/research" className="researchLink">গবেষণার বিবরণ</a></header>
  <section className="productIntro"><p>বাংলা চলচ্চিত্রের প্লট থেকে দর্শক-প্রতিক্রিয়া</p><h1>প্লট দিন, দুই ধরনের মন্তব্য দেখুন</h1><span>প্রতিটি মন্তব্য generation-এর পরে plot-এর সঙ্গে স্বয়ংক্রিয়ভাবে মিলিয়ে দেখা হবে। এটি audience বা box-office prediction নয়।</span></section>
  <section className="composer"><div className={`connectionState ${online===true?'online':online===false?'offline':''}`}>{online===true?'Backend connected':online===false?'Backend পাওয়া যাচ্ছে না':'Backend পরীক্ষা হচ্ছে…'}</div><label htmlFor="plot">সিনেমার প্লট বা synopsis</label><textarea id="plot" value={plot} maxLength={6000} onChange={e=>setPlot(e.target.value)} placeholder="এখানে বাংলা প্লট লিখুন…"/><div className="composerMeta"><span>{chars}/6000</span><button type="button" onClick={()=>setPlot('রাশেদ তার নিখোঁজ ভাইকে খুঁজতে গিয়ে শহরের ক্ষমতাবান এক পরিবারের গোপন অপরাধ আবিষ্কার করে। শেষ দৃশ্যে সে সত্য প্রকাশ করবে নাকি পরিবারকে রক্ষা করবে—এই সিদ্ধান্তের মুখোমুখি হয়।')}>উদাহরণ ব্যবহার করুন</button></div><div className="choiceRow">{([['both','দুই ধরনের'],['0','সাধারণ'],['1','নির্দিষ্ট']] as const).map(([v,l])=><button type="button" key={v} aria-pressed={target===v} className={target===v?'chosen':''} onClick={()=>setTarget(v)}>{l}</button>)}</div><button type="button" className="primaryAction" disabled={!plot.trim()||loading} onClick={generate}>{loading?'মন্তব্য তৈরি ও যাচাই হচ্ছে…':'মন্তব্য তৈরি করুন'}</button><p className="modeNote"><b>Seeded live mode</b><span>Seed 42 ব্যবহৃত হয়; hosted model-এর output সামান্য বদলাতে পারে</span></p>{error&&<p className="productError" role="alert">{error} <button type="button" onClick={generate}>আবার চেষ্টা করুন</button></p>}</section>
  {(loading||result)&&<section className="resultsArea" aria-live="polite"><div className="resultsTitle"><h2>তৈরি করা মন্তব্য</h2>{loading&&<span>প্রথম run-এ local artifacts load হতে সময় লাগতে পারে</span>}</div><div className="resultGrid">{LEVELS.filter(x=>target==='both'||String(x.id)===target).map(level=>{const output=result?.outputs.find(x=>x.target_level===level.id);const faith=output?.faithfulness;return <article className="responseCard" key={level.id}><header><div><b>{level.label}</b><small>{level.note}</small></div>{output&&<span className={output.gave_up?'axisFail':'axisPass'}>{output.gave_up?'Level অনিশ্চিত':'Level matched'}</span>}</header><div className="responseText">{output?.final.draft||'তৈরি হচ্ছে…'}</div>{faith&&<div className={`faithBox ${faith.status}`}><div><b>{FAITH_LABEL[faith.status]}</b></div><p>{faith.explanation}</p>{faith.unsupported_claims.length>0&&<ul>{faith.unsupported_claims.map((claim,i)=><li key={i}>{claim}</li>)}</ul>}<small>Generation-এর পরের automated plot check; correction loop-এর অংশ নয় এবং human-validated metric নয়</small></div>}{output&&<div className="agentActivity"><div className="activityHead"><b>এই run-এ bounded component activity</b><span>{output.llm_calls} generation-loop LLM call</span></div><ul><li><i className="ran">✓</i><span><b>Researcher</b><small>R1-only; FAIL হলে feedback-anchored retrieval</small></span></li><li><i className="ran">✓</i><span><b>Writer</b><small>{output.writer_calls} draft call</small></span></li><li><i className="ran">✓</i><span><b>Critic</b><small>Verifier-A + symbolic diagnostic</small></span></li><li className={output.reflector_calls?'':'skipped'}><i>{output.reflector_calls?'✓':'—'}</i><span><b>Reflector</b><small>{output.reflector_calls?`${output.reflector_calls} correction call`:'প্রথম attempt PASS—প্রয়োজন হয়নি'}</small></span></li><li className={faith?.status==='check_failed'?'skipped':''}><i>{faith?.status==='check_failed'?'!':'✓'}</i><span><b>Plot Judge</b><small>{faith?.status==='check_failed'?'post-generation check ব্যর্থ':'post-generation check complete'}</small></span></li></ul></div>}{output&&<details className="expertTrace"><summary>Correction trace দেখুন <span>{output.attempts.length} attempt</span></summary>{output.attempts.map(a=><div className="traceItem" key={a.attempt}><div><b>Attempt {a.attempt}</b><span>{a.verdict}</span></div><p>{a.draft}</p><small>Level score {a.neural_score.toFixed(3)} · Symbolic diagnostic {a.symbolic_score.toFixed(3)}</small><small className="retrievedIds">R1 evidence: {a.retrieved.join(', ')}</small>{a.feedback&&<blockquote>{a.feedback}</blockquote>}</div>)}</details>}</article>})}</div></section>}
  <footer className="productFooter"><span>Local research demonstration</span><a href="/research">Method, safeguards ও frozen experiment দেখুন →</a></footer>
 </main>;
}
