"""Order thesis references by first citation, retaining the uncited registry."""

from __future__ import annotations

import csv
import re
from pathlib import Path

from src.common.seed import set_seed


ROOT = Path(__file__).resolve().parents[2]
BIB = ROOT / "docs" / "references_ieee.bib"
MAP = ROOT / "docs" / "reference_key_map_full.csv"
DOCUMENTS = [
    ROOT / "docs" / "thesis_front_matter.md",
    *sorted((ROOT / "docs" / "chapters").glob("chapter*.md")),
    ROOT / "docs" / "generative_ai_declaration.md",
    *sorted((ROOT / "docs" / "appendices").glob("appendix*.md")),
]
ENTRY_RE = re.compile(r"(?ms)^@(\w+)\{(b\d+),(.*?)^\}")
CITE_RE = re.compile(r"@(?P<key>b\d+)\b")


def main() -> None:
    set_seed()
    text = BIB.read_text(encoding="utf-8")
    entries = {m.group(2): (m.group(1), m.group(3)) for m in ENTRY_RE.finditer(text)}
    first: list[str] = []
    for path in DOCUMENTS:
        if not path.exists():
            continue
        for match in CITE_RE.finditer(path.read_text(encoding="utf-8")):
            key = match.group("key")
            if key not in entries:
                raise ValueError(f"unresolved citation {key} in {path}")
            if key not in first:
                first.append(key)
    remaining = sorted((key for key in entries if key not in first), key=lambda x: int(x[1:]))
    ordered = first + remaining
    remap = {old: f"b{i}" for i, old in enumerate(ordered, start=1)}

    for path in DOCUMENTS:
        if path.exists():
            original = path.read_text(encoding="utf-8")
            updated = CITE_RE.sub(lambda m: "@" + remap[m.group("key")], original)
            path.write_text(updated, encoding="utf-8", newline="\n")

    rendered = []
    for old in ordered:
        kind, body = entries[old]
        rendered.append(f"@{kind}{{{remap[old]},{body}\n}}")
    header = (
        "% Canonical thesis bibliography. Render with IEEEtran or IEEE CSL.\n"
        "% Cited entries follow first appearance in thesis assembly order; uncited registry entries follow.\n"
        "% Generated by src/common/build_thesis_bibliography.py and ordered by order_thesis_bibliography.py.\n\n"
    )
    BIB.write_text(header + "\n\n".join(rendered) + "\n", encoding="utf-8", newline="\n")

    with MAP.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    by_old = {row["b_key"]: row for row in rows}
    for old, new in remap.items():
        by_old[old]["b_key"] = new
        if old in first:
            by_old[old]["reading_status"] = "chapter_cited"
    ordered_rows = [by_old[old] for old in ordered]
    with MAP.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(ordered_rows[0]))
        writer.writeheader()
        writer.writerows(ordered_rows)
    print(f"cited={len(first)} total={len(ordered)}")


if __name__ == "__main__":
    main()
